apiVersion: polaris.synthesis.co.za/v1alpha1
kind: PolarisBuildStep
metadata:
  name: gamestarter
  labels:
    polaris-project: rev
    polaris-component: gamestarter
    app: {{ template "thischart.name" $ }}
    chart: {{ template "thischart.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}  
spec:
  pipeline: rev
  builds:
  - name: gamestarter
    dockerfilelocation: images/gamestarter
    containerregistry: rev-gamestarter
    tag: 1.0.0
