apiVersion: polaris.synthesis.co.za/v1alpha1
kind: PolarisBuildStep
metadata:
  name: randomplayer
  labels:
    polaris-project: rev
    polaris-component: randomplayer
    app: {{ template "thischart.name" $ }}
    chart: {{ template "thischart.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}  
spec:
  pipeline: rev
  builds:
  - name: randomplayer
    dockerfilelocation: images/randomplayer
    containerregistry: rev-randomplayer
    tag: 1.0.0
