apiVersion: polaris.synthesis.co.za/v1alpha1
kind: PolarisBuildPipeline
metadata:
  name: rev
  labels:
    polaris-project: rev
    app: {{ template "thischart.name" $ }}
    chart: {{ template "thischart.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  source:
    codecommitrepo: rev
    branch: master
