apiVersion: polaris.synthesis.co.za/v1alpha1
kind: PolarisBuildStep
metadata:
  name: lagchecker
  labels:
    polaris-project: rev
    polaris-component: lagchecker
    app: {{ template "thischart.name" $ }}
    chart: {{ template "thischart.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}  
spec:
  pipeline: rev
  builds:
  - name: lagchecker
    dockerfilelocation: images/lagchecker
    containerregistry: rev-lagchecker
    tag: 1.0.0
