
resource_name: createtopics

replicas: 1

image:
  repository: polaris://rev-createtopics
  tag: 1.0.0
  pullPolicy: Always

environment:
  kafka_bootstrap_servers: polaris-kafka-cp-kafka.default:9092

resources:
  requests:
    cpu: 250m
    memory: "256Mi"
  limits:
    cpu: 500m
    memory: "512Mi"