apiVersion: polaris.synthesis.co.za/v1alpha1
kind: PolarisBuildStep
metadata:
  name: createtopics
  labels:
    polaris-project: rev
    polaris-component: createtopics
    app: {{ template "thischart.name" $ }}
    chart: {{ template "thischart.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}  
spec:
  pipeline: rev
  builds:
  - name: createtopics
    dockerfilelocation: images/createtopics
    containerregistry: rev-createtopics
    tag: 1.0.0
