apiVersion: polaris.synthesis.co.za/v1alpha1
kind: PolarisBuildStep
metadata:
  name: gamesaver
  labels:
    polaris-project: rev
    polaris-component: gamesaver
    app: {{ template "thischart.name" $ }}
    chart: {{ template "thischart.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}  
spec:
  pipeline: rev
  builds:
  - name: gamesaver
    dockerfilelocation: images/gamesaver
    containerregistry: rev-gamesaver
    tag: 1.0.0
