
resource_name: gamestarter

replicas: 3

image:
  repository: polaris://rev-gamestarter
  tag: 1.0.0
  pullPolicy: Always

environment:
  kafka_bootstrap_servers: polaris-kafka-cp-kafka.default:9092

resources:
  requests:
    cpu: 50m
    memory: "256Mi"
  limits:
    cpu: 100m
    memory: "512Mi"